version: '3'
services: 
  db_server:
    image: mongo:3.4
  backend:
    image: node:8.1
    volumes: 
      - ./back:/backend/
    ports:
      - 3000:3000
    command: bash -c "cd /backend && npm i && node app"
  frontend:
    image: nginx:1.13
    volumes:
      - ./front:/usr/share/nginx/html/
    ports:
      - 8080:80
    